on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: dutymachine/weixin-archive-action@v1
        env:
          TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}